In [1]:
import numpy as np
import pandas as pd

In [2]:
# Question 1

np.__version__

'1.21.2'

In [3]:
# Question 2

pd.__version__

'1.3.2'

In [4]:
data = pd.read_csv("homework_data.csv")

In [5]:
data.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

In [6]:
# Question 3

data.loc[data["Make"]=="BMW", "MSRP"].mean()

61546.76347305389

In [7]:
# Question 4

data.loc[data["Year"]>=2015, "Engine HP"].isna().sum()

51

In [8]:
# Question 5

mean_engine_HP_before = data["Engine HP"].mean()
round(mean_engine_HP_before)

249

In [9]:
mean_engine_HP_after = data["Engine HP"].fillna(mean_engine_HP_before).mean()
round(mean_engine_HP_after)

249

In [10]:
mean_engine_HP_before == mean_engine_HP_after

True

In [11]:
# Question 6

X = (data.loc[data["Make"]=="Rolls-Royce", ["Engine HP", "Engine Cylinders", "highway MPG"]]
     .drop_duplicates()
     .values)
X

array([[325.,   8.,  15.],
       [563.,  12.,  19.],
       [563.,  12.,  21.],
       [563.,  12.,  20.],
       [322.,  12.,  15.],
       [453.,  12.,  19.],
       [624.,  12.,  21.]])

In [12]:
XTX = X.T.dot(X)
XTX

array([[1.754801e+06, 3.965600e+04, 6.519600e+04],
       [3.965600e+04, 9.280000e+02, 1.500000e+03],
       [6.519600e+04, 1.500000e+03, 2.454000e+03]])

In [13]:
np.linalg.inv(XTX).sum()

0.032212320677486195

In [14]:
# Question 7

y = np.array([1000, 1100, 900, 1200, 1000, 850, 1300])
y

array([1000, 1100,  900, 1200, 1000,  850, 1300])

In [15]:
w = np.linalg.inv(XTX).dot(X.T).dot(y)
w

array([ 0.19989598, 31.02612262, 31.65378877])

In [16]:
w[0]

0.19989598183186175